modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="freehandzs_utilities"
version="1.0.0"
displayName="FreehandZ's Utilities"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Mickey, MCreator"

[[dependencies.freehandzs_utilities]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"



